/**
 * Centrifugal Casing Tab Configuration
 * Columns and form fields derived from Prisma schema.
 * columns: table display (key can be nested e.g. "casing.model")
 * formFields: add/edit form (excludes id, createdAt, updatedAt)
 */

const col = (key, label, type = "text") => ({ key, label, type });
const displayCol = (key, label) => ({ key, label });

export const CASING_TAB_CONFIG = {
  "casing-pricing": {
    columns: [
      displayCol("id", "ID"),
      displayCol("type", "Type"),
      displayCol("model", "Model"),
      displayCol("sizeMm", "Size (mm)"),
      displayCol("modelAndSize", "Model & Size"),
    ],
    formFields: [
      col("type", "Type"),
      col("model", "Model"),
      col("sizeMm", "Size (mm)", "number"),
      col("modelAndSize", "Model & Size"),
    ],
  },

  "casing-volutes": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("volute2mmWeightKgWithoutScrap", "2mm Weight w/o Scrap"),
      displayCol("volute2mmScrapPct", "2mm Scrap %"),
      displayCol("volute2mmWeightKgWithScrap", "2mm Weight w/ Scrap"),
      displayCol("volute2mmSheetMetalDimensionsMm", "2mm Dimensions"),
      displayCol("volute1mmWeightKgWithoutScrap", "1mm Weight w/o Scrap"),
      displayCol("volute1mmScrapPct", "1mm Scrap %"),
      displayCol("volute1mmWeightKgWithScrap", "1mm Weight w/ Scrap"),
      displayCol("volute1mmSheetMetalDimensionsMm", "1mm Dimensions"),
      displayCol("volute1mmLaserTimeMin", "1mm Laser Time"),
      displayCol("volute1mmRolling", "1mm Rolling"),
      displayCol("volute1mmSheetMetalOverlapping", "1mm Overlapping"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("volute2mmWeightKgWithoutScrap", "2mm Weight w/o Scrap", "number"),
      col("volute2mmScrapPct", "2mm Scrap %", "number"),
      col("volute2mmSheetMetalDimensionsMm", "2mm Dimensions"),
      col("volute1mmWeightKgWithoutScrap", "1mm Weight w/o Scrap", "number"),
      col("volute1mmScrapPct", "1mm Scrap %", "number"),
      col("volute1mmSheetMetalDimensionsMm", "1mm Dimensions"),
      col("volute1mmLaserTimeMin", "1mm Laser Time", "number"),
      col("volute1mmRolling", "1mm Rolling", "number"),
      col("volute1mmSheetMetalOverlapping", "1mm Overlapping", "number"),
    ],
  },

  "casing-frames": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("angleBarWeightKgWithoutScrap", "Angle Bar Weight"),
      displayCol("angleBarScrapPct", "Angle Bar Scrap %"),
      displayCol("angleBarDimensionsMm", "Angle Bar Dims"),
      displayCol("supportWeightKgWithoutScrap", "Support Weight"),
      displayCol("supportScrapPct", "Support Scrap %"),
      displayCol("supportSheetMetalDimensionsMm", "Support Dims"),
      displayCol("supportLaserTimeMin", "Support Laser"),
      displayCol("supportCasingCircumferenceM", "Support Circumf"),
      displayCol("supportPaintingLe", "Support Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("angleBarWeightKgWithoutScrap", "Angle Bar Weight", "number"),
      col("angleBarScrapPct", "Angle Bar Scrap %", "number"),
      col("angleBarDimensionsMm", "Angle Bar Dims"),
      col("supportWeightKgWithoutScrap", "Support Weight", "number"),
      col("supportScrapPct", "Support Scrap %", "number"),
      col("supportSheetMetalDimensionsMm", "Support Dims"),
      col("supportLaserTimeMin", "Support Laser", "number"),
      col("supportCasingCircumferenceM", "Support Circumf", "number"),
      col("supportPaintingLe", "Support Painting", "number"),
    ],
  },

  "casing-impellers": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("bladesWeightKgWithoutScrap", "Blades Weight"),
      displayCol("bladesScrapPct", "Blades Scrap %"),
      displayCol("bladesSheetMetalDimensionsMm", "Blades Dims"),
      displayCol("plateWeightKgWithoutScrap", "Plate Weight"),
      displayCol("plateScrapPct", "Plate Scrap %"),
      displayCol("plateSheetMetalDimensionsMm", "Plate Dims"),
      displayCol("plateCentrifugalImpellerRigCostPcs", "Plate Rig Cost"),
      displayCol("plateLaserTimeMin", "Plate Laser"),
      displayCol("plateCasingCircumferenceM", "Plate Circumf"),
      displayCol("platePaintingLe", "Plate Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("bladesWeightKgWithoutScrap", "Blades Weight", "number"),
      col("bladesScrapPct", "Blades Scrap %", "number"),
      col("bladesSheetMetalDimensionsMm", "Blades Dims"),
      col("plateWeightKgWithoutScrap", "Plate Weight", "number"),
      col("plateScrapPct", "Plate Scrap %", "number"),
      col("plateSheetMetalDimensionsMm", "Plate Dims"),
      col("plateCentrifugalImpellerRigCostPcs", "Plate Rig Cost", "number"),
      col("plateLaserTimeMin", "Plate Laser", "number"),
      col("plateCasingCircumferenceM", "Plate Circumf", "number"),
      col("platePaintingLe", "Plate Painting", "number"),
    ],
  },

  "casing-funnels": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("funnel15mmWeightKgWithoutScrap", "1.5mm Weight"),
      displayCol("funnel15mmScrapPct", "1.5mm Scrap %"),
      displayCol("funnel15mmSheetMetalDimensionsMm", "1.5mm Dims"),
      displayCol("funnel15mmDieCastingLePc", "1.5mm Die Casting"),
      displayCol("funnel15mmFunnelMachiningLe", "1.5mm Machining"),
      displayCol("funnel15mmGalvanizeLe", "1.5mm Galvanize"),
      displayCol("funnel3mmWeightKgWithoutScrap", "3mm Weight"),
      displayCol("funnel3mmScrapPct", "3mm Scrap %"),
      displayCol("funnel3mmSheetMetalDimensionsMm", "3mm Dims"),
      displayCol("funnel3mmDieCastingLePc", "3mm Die Casting"),
      displayCol("funnel3mmFunnelMachiningLe", "3mm Machining"),
      displayCol("funnel3mmPaintingLe", "3mm Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("funnel15mmWeightKgWithoutScrap", "1.5mm Weight", "number"),
      col("funnel15mmScrapPct", "1.5mm Scrap %", "number"),
      col("funnel15mmSheetMetalDimensionsMm", "1.5mm Dims"),
      col("funnel15mmDieCastingLePc", "1.5mm Die Casting", "number"),
      col("funnel15mmFunnelMachiningLe", "1.5mm Machining", "number"),
      col("funnel15mmGalvanizeLe", "1.5mm Galvanize", "number"),
      col("funnel3mmWeightKgWithoutScrap", "3mm Weight", "number"),
      col("funnel3mmScrapPct", "3mm Scrap %", "number"),
      col("funnel3mmSheetMetalDimensionsMm", "3mm Dims"),
      col("funnel3mmDieCastingLePc", "3mm Die Casting", "number"),
      col("funnel3mmFunnelMachiningLe", "3mm Machining", "number"),
      col("funnel3mmPaintingLe", "3mm Painting", "number"),
    ],
  },

  "casing-sleeve-shafts": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("sleeveWeightKgWithoutScrap", "Sleeve Weight"),
      displayCol("sleeveScrapPct", "Sleeve Scrap %"),
      displayCol("sleeveSheetMetalDimensionsMm", "Sleeve Dims"),
      displayCol("sleeveManufacturingLePc", "Sleeve Mfg"),
      displayCol("shaftWeightKgWithoutScrap", "Shaft Weight"),
      displayCol("shaftScrapPct", "Shaft Scrap %"),
      displayCol("shaftSheetMetalDimensionsMm", "Shaft Dims"),
      displayCol("shaftManufacturingLePc", "Shaft Mfg"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("sleeveWeightKgWithoutScrap", "Sleeve Weight", "number"),
      col("sleeveScrapPct", "Sleeve Scrap %", "number"),
      col("sleeveSheetMetalDimensionsMm", "Sleeve Dims"),
      col("sleeveManufacturingLePc", "Sleeve Mfg", "number"),
      col("shaftWeightKgWithoutScrap", "Shaft Weight", "number"),
      col("shaftScrapPct", "Shaft Scrap %", "number"),
      col("shaftSheetMetalDimensionsMm", "Shaft Dims"),
      col("shaftManufacturingLePc", "Shaft Mfg", "number"),
    ],
  },

  "casing-matching-flanges": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("flange3mmWeightKgWithoutScrap", "Flange Weight"),
      displayCol("flange3mmScrapPct", "Flange Scrap %"),
      displayCol("flange3mmSheetMetalDimensionsMm", "Flange Dims"),
      displayCol("flange3mmLaserTimeMin", "Laser Time"),
      displayCol("flange3mmRolling", "Rolling"),
      displayCol("flange3mmCasingCircumferenceM", "Circumf"),
      displayCol("selfAligningBearingHousingLe", "Bearing Housing"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("flange3mmWeightKgWithoutScrap", "Flange Weight", "number"),
      col("flange3mmScrapPct", "Flange Scrap %", "number"),
      col("flange3mmSheetMetalDimensionsMm", "Flange Dims"),
      col("flange3mmLaserTimeMin", "Laser Time", "number"),
      col("flange3mmRolling", "Rolling", "number"),
      col("flange3mmCasingCircumferenceM", "Circumf", "number"),
      col("selfAligningBearingHousingLe", "Bearing Housing", "number"),
    ],
  },

  "casing-bearing-assemblies": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("boltsNutsKg", "Bolts+Nuts (kg)"),
      displayCol("assemblyLaboursPerShaft", "Assembly Labours/Shaft"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("boltsNutsKg", "Bolts+Nuts (kg)", "number"),
      col("assemblyLaboursPerShaft", "Assembly Labours/Shaft", "number"),
    ],
  },

  "casing-fan-bases": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("weightKgWithoutScrap", "Weight w/o Scrap"),
      displayCol("scrapPct", "Scrap %"),
      displayCol("weightKgWithScrap", "Weight w/ Scrap"),
      displayCol("sheetMetalDimensionsMm", "Dimensions"),
      displayCol("laserTimeMin", "Laser Time"),
      displayCol("bendingLine", "Bending Line"),
      displayCol("paintingLe", "Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("weightKgWithoutScrap", "Weight w/o Scrap", "number"),
      col("scrapPct", "Scrap %", "number"),
      col("sheetMetalDimensionsMm", "Dimensions"),
      col("laserTimeMin", "Laser Time", "number"),
      col("bendingLine", "Bending Line", "number"),
      col("paintingLe", "Painting", "number"),
    ],
  },

  "casing-belt-covers": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("weightKgWithoutScrap", "Weight w/o Scrap"),
      displayCol("scrapPct", "Scrap %"),
      displayCol("weightKgWithScrap", "Weight w/ Scrap"),
      displayCol("sheetMetalDimensionsMm", "Dimensions"),
      displayCol("laserTimeMin", "Laser Time"),
      displayCol("casingCircumferenceM", "Circumf"),
      displayCol("paintingLe", "Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("weightKgWithoutScrap", "Weight w/o Scrap", "number"),
      col("scrapPct", "Scrap %", "number"),
      col("sheetMetalDimensionsMm", "Dimensions"),
      col("laserTimeMin", "Laser Time", "number"),
      col("casingCircumferenceM", "Circumf", "number"),
      col("paintingLe", "Painting", "number"),
    ],
  },

  "casing-motor-bases": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("weightKgWithoutScrap", "Weight w/o Scrap"),
      displayCol("scrapPct", "Scrap %"),
      displayCol("weightKgWithScrap", "Weight w/ Scrap"),
      displayCol("sheetMetalDimensionsMm", "Dimensions"),
      displayCol("laserTimeMin", "Laser Time"),
      displayCol("bendingLine", "Bending Line"),
      displayCol("studNutPriceLe", "Stud & Nut"),
      displayCol("paintingLe", "Painting"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("weightKgWithoutScrap", "Weight w/o Scrap", "number"),
      col("scrapPct", "Scrap %", "number"),
      col("sheetMetalDimensionsMm", "Dimensions"),
      col("laserTimeMin", "Laser Time", "number"),
      col("bendingLine", "Bending Line", "number"),
      col("studNutPriceLe", "Stud & Nut", "number"),
      col("paintingLe", "Painting", "number"),
    ],
  },

  "casing-accessories": {
    columns: [
      displayCol("id", "ID"),
      displayCol("casing.model", "Casing Model"),
      displayCol("casing.sizeMm", "Size (mm)"),
      displayCol("vibrationIsolatorsLe", "Vibration Isolators"),
      displayCol("vinylStickersLe", "Vinyl Stickers"),
      displayCol("namePlateLe", "Name Plate"),
      displayCol("packingLe", "Packing"),
      displayCol("labourCostLe", "Labour Cost"),
      displayCol("internalTransportationLe", "Internal Transport"),
    ],
    formFields: [
      col("casingId", "Casing ID", "number"),
      col("vibrationIsolatorsLe", "Vibration Isolators", "number"),
      col("vinylStickersLe", "Vinyl Stickers", "number"),
      col("namePlateLe", "Name Plate", "number"),
      col("packingLe", "Packing", "number"),
      col("labourCostLe", "Labour Cost", "number"),
      col("internalTransportationLe", "Internal Transport", "number"),
    ],
  },
};
