-- CreateTable
CREATE TABLE "fan_data" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "No" INTEGER,
    "Model" TEXT,
    "AF-S" INTEGER,
    "AF-L" INTEGER,
    "WF" INTEGER,
    "ARTF" INTEGER,
    "SF" INTEGER,
    "ABSF-C" INTEGER,
    "ABSF-S" INTEGER,
    "SABF" INTEGER,
    "SARTF" INTEGER,
    "AJF" INTEGER,
    "bladesSymbol" TEXT NOT NULL,
    "bladesMaterial" TEXT NOT NULL,
    "noBlades" INTEGER NOT NULL,
    "bladesAngle" REAL NOT NULL,
    "hubType" INTEGER NOT NULL,
    "impellerConf" TEXT NOT NULL,
    "impellerInnerDia" REAL NOT NULL,
    "desigDensity" REAL NOT NULL,
    "RPM" REAL NOT NULL,
    "airFlow" TEXT NOT NULL,
    "totPressure" TEXT NOT NULL,
    "velPressure" TEXT NOT NULL,
    "staticPressure" TEXT NOT NULL,
    "fanInputPow" TEXT NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);

-- CreateTable
CREATE TABLE "motor_data" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "material" TEXT,
    "model" TEXT,
    "powerKW" REAL,
    "speedRPM" REAL,
    "NoPoles" INTEGER,
    "rated" TEXT,
    "DOL" TEXT,
    "starDelta" TEXT,
    "powerFactor" REAL,
    "Phase" INTEGER,
    "frameSize" INTEGER,
    "shaftDia" REAL,
    "shaftLength" REAL,
    "shaftFeather" REAL,
    "IE" INTEGER,
    "frontBear" TEXT,
    "rearBear" TEXT,
    "noiseLvl" INTEGER,
    "weightKg" REAL,
    "effCurve" TEXT,
    "NoCapacitors" INTEGER,
    "NoPhases" INTEGER,
    "insClass" TEXT,
    "powerHorse" REAL,
    "netpower" REAL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
